// components/mapData.js
//
// Примерная игровая карта Прокорівка — Сушки (30x30 гексов)
// Все координаты — axial (q, r)

const COLORS = {
  forest:      "#9edb8d",
  island:      "#b6e3a1",
  field:      "#d9ffbf",
  village:        "#dcdcdc",

  lake:        "#7ec5ff",
  river:       "#66b4ff",
  lough_river:   "#89c9ff",
  great_river:   "#4a9de0",
};

const mapData = [

  //
  // Прохоровка
  //
  { q: -1,  r: -2,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: 1,  r: -2,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: 2,  r: -2,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: -1,  r: -1,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: 0,  r: -1,  name: "Домик", type: "village", color: COLORS.village },
  { q: 1,  r: -1,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: 2,  r: -1,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: 3,  r: -1,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: 4,  r: -1,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: -1,  r: 0,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: 0,  r: 0,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: 1,  r: 0,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: 2,  r: 0,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: 3,  r: 0,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: 4,  r: 0,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: -1,  r: 1,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: 0,  r: 1,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: 1,  r: 1,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: -1,  r: 2,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: 5,  r: -1,  name: "Прохорівка", type: "village", color: COLORS.village },
  { q: 6,  r: -2,  name: "Прохорівка", type: "village", color: COLORS.village },

  //
  // Сушки
  //
  { q: 7,  r: 2,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 4,  r: 3,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 5,  r: 3,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 6,  r: 3,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 7,  r: 3,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 4,  r: 4,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 5,  r: 4,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 6,  r: 4,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 7,  r: 4,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 3,  r: 5,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 4,  r: 5,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 5,  r: 5,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 8,  r: 5,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 8,  r: 2,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 9,  r: 2,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 9,  r: 3,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 9,  r: 4,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 8,  r: 1,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 9,  r: 1,  name: "Сушки", type: "village", color: COLORS.village },
  { q: 9,  r: 0,  name: "Сушки", type: "village", color: COLORS.village },

  //
  // Пекари
  //
  { q: -8,  r: 1,  name: "Сушки", type: "village", color: COLORS.village },
  { q: -8,  r: 0,  name: "Сушки", type: "village", color: COLORS.village },
  { q: -9,  r: 1,  name: "Сушки", type: "village", color: COLORS.village },

  //
  // Келеберда
  //
  { q: -2,  r: -6,  name: "Келеберда", type: "village", color: COLORS.village },
  { q: -1,  r: -5,  name: "Келеберда", type: "village", color: COLORS.village },
  { q: -1,  r: -6,  name: "Келеберда", type: "village", color: COLORS.village },
  { q: -1,  r: -7,  name: "Келеберда", type: "village", color: COLORS.village },
  { q: 0,  r: -6,  name: "Келеберда", type: "village", color: COLORS.village },
  { q: 0,  r: -7,  name: "Келеберда", type: "village", color: COLORS.village },

  //
  // Озера
  //
  { q: -1,  r: 3,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: 0,  r: 4,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: -4,  r: -1,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: -7,  r: 9,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: -8,  r: 7,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: -8,  r: 8,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: 1,  r: 9,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: 1,  r: 10,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: -1,  r: 13,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: -2,  r: 14,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: -11,  r: 14,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: -11,  r: 15,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: -12,  r: 7,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: -11,  r: 7,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: -9,  r: 5,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: -9,  r: 6,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: -12,  r: 9,  name: "Озеро", type: "lake", color: COLORS.lake },
  { q: -9,  r: 7,  name: "Озеро", type: "lake", color: COLORS.lake },

  //
  // Поля
  //
  { q: 2,  r: 2,  name: "Поле", type: "field", color: COLORS.field },
  { q: 2,  r: 3,  name: "Поле", type: "field", color: COLORS.field },
  { q: 2,  r: 4,  name: "Поле", type: "field", color: COLORS.field },
  { q: 2,  r: 5,  name: "Поле", type: "field", color: COLORS.field },
  { q: 2,  r: 6,  name: "Поле", type: "field", color: COLORS.field },
  { q: 3,  r: 2,  name: "Поле", type: "field", color: COLORS.field },
  { q: 3,  r: 3,  name: "Поле", type: "field", color: COLORS.field },
  { q: 3,  r: 4,  name: "Поле", type: "field", color: COLORS.field },
  { q: 3,  r: 6,  name: "Поле", type: "field", color: COLORS.field },
  { q: 4,  r: 7,  name: "Поле", type: "field", color: COLORS.field },
  { q: 4,  r: 8,  name: "Поле", type: "field", color: COLORS.field },
  { q: 4,  r: 9,  name: "Поле", type: "field", color: COLORS.field },
  { q: 5,  r: 7,  name: "Поле", type: "field", color: COLORS.field },
  { q: 5,  r: 8,  name: "Поле", type: "field", color: COLORS.field },
  { q: 6,  r: 6,  name: "Поле", type: "field", color: COLORS.field },
  { q: 6,  r: 7,  name: "Поле", type: "field", color: COLORS.field },
  { q: 7,  r: 6,  name: "Поле", type: "field", color: COLORS.field },
  { q: 7,  r: -1,  name: "Поле", type: "field", color: COLORS.field },
  { q: 8,  r: -1,  name: "Поле", type: "field", color: COLORS.field },
  { q: 9,  r: -1,  name: "Поле", type: "field", color: COLORS.field },
  { q: 7,  r: -2,  name: "Поле", type: "field", color: COLORS.field },
  { q: 8,  r: -2,  name: "Поле", type: "field", color: COLORS.field },
  { q: 9,  r: -2,  name: "Поле", type: "field", color: COLORS.field },
  { q: 7,  r: -3,  name: "Поле", type: "field", color: COLORS.field },
  { q: 8,  r: -3,  name: "Поле", type: "field", color: COLORS.field },
  { q: 9,  r: -3,  name: "Поле", type: "field", color: COLORS.field },
  { q: 7,  r: -4,  name: "Поле", type: "field", color: COLORS.field },
  { q: 8,  r: -4,  name: "Поле", type: "field", color: COLORS.field },
  { q: 9,  r: -4,  name: "Поле", type: "field", color: COLORS.field },
  { q: 7,  r: -5,  name: "Поле", type: "field", color: COLORS.field },
  { q: 8,  r: -5,  name: "Поле", type: "field", color: COLORS.field },
  { q: 9,  r: -5,  name: "Поле", type: "field", color: COLORS.field },
  { q: 7,  r: -6,  name: "Поле", type: "field", color: COLORS.field },
  { q: 8,  r: -6,  name: "Поле", type: "field", color: COLORS.field },
  { q: 9,  r: -6,  name: "Поле", type: "field", color: COLORS.field },
  { q: 8,  r: -7,  name: "Поле", type: "field", color: COLORS.field },
  { q: 9,  r: -7,  name: "Поле", type: "field", color: COLORS.field },
  { q: -8,  r: 2,  name: "Поле", type: "field", color: COLORS.field },
  { q: -8,  r: 3,  name: "Поле", type: "field", color: COLORS.field },
  { q: -8,  r: 4,  name: "Поле", type: "field", color: COLORS.field },
  { q: -9,  r: 2,  name: "Поле", type: "field", color: COLORS.field },
  { q: -9,  r: 3,  name: "Поле", type: "field", color: COLORS.field },
  { q: -9,  r: 4,  name: "Поле", type: "field", color: COLORS.field },
  { q: -10,  r: 2,  name: "Поле", type: "field", color: COLORS.field },
  { q: -10,  r: 3,  name: "Поле", type: "field", color: COLORS.field },
  { q: -10,  r: 4,  name: "Поле", type: "field", color: COLORS.field },
  { q: -11,  r: 3,  name: "Поле", type: "field", color: COLORS.field },
  { q: -11,  r: 4,  name: "Поле", type: "field", color: COLORS.field },
  { q: -12,  r: 4,  name: "Поле", type: "field", color: COLORS.field },
  { q: -10,  r: 5,  name: "Поле", type: "field", color: COLORS.field },
  { q: -11,  r: 5,  name: "Поле", type: "field", color: COLORS.field },
  { q: -12,  r: 5,  name: "Поле", type: "field", color: COLORS.field },
  { q: -13,  r: 5,  name: "Поле", type: "field", color: COLORS.field },
  { q: -13,  r: 6,  name: "Поле", type: "field", color: COLORS.field },
  { q: -6,  r: 15,  name: "Поле", type: "field", color: COLORS.field },
  { q: -7,  r: 15,  name: "Поле", type: "field", color: COLORS.field },
  { q: -8,  r: 15,  name: "Поле", type: "field", color: COLORS.field },
  { q: -8,  r: 14,  name: "Поле", type: "field", color: COLORS.field },
  { q: -9,  r: 15,  name: "Поле", type: "field", color: COLORS.field },
  { q: -9,  r: 14,  name: "Поле", type: "field", color: COLORS.field },
  { q: -10,  r: 15,  name: "Поле", type: "field", color: COLORS.field },
  { q: -12,  r: 15,  name: "Поле", type: "field", color: COLORS.field },
  { q: -13,  r: 15,  name: "Поле", type: "field", color: COLORS.field },
  { q: -13,  r: 14,  name: "Поле", type: "field", color: COLORS.field },
  { q: -12,  r: 14,  name: "Поле", type: "field", color: COLORS.field },
  { q: -13,  r: 13,  name: "Поле", type: "field", color: COLORS.field },
  { q: -12,  r: 13,  name: "Поле", type: "field", color: COLORS.field },
  { q: -10,  r: 12,  name: "Поле", type: "field", color: COLORS.field },
  { q: -11,  r: 13,  name: "Поле", type: "field", color: COLORS.field },
  { q: -13,  r: 7,  name: "Поле", type: "field", color: COLORS.field },
  { q: -13,  r: 8,  name: "Поле", type: "field", color: COLORS.field },
  { q: -13,  r: 9,  name: "Поле", type: "field", color: COLORS.field },
  { q: -13,  r: 10,  name: "Поле", type: "field", color: COLORS.field },
  { q: -12,  r: 8,  name: "Поле", type: "field", color: COLORS.field },
  { q: -12,  r: 10,  name: "Поле", type: "field", color: COLORS.field },
  { q: -12,  r: 11,  name: "Поле", type: "field", color: COLORS.field },
  { q: -11,  r: 8,  name: "Поле", type: "field", color: COLORS.field },
  { q: -11,  r: 9,  name: "Поле", type: "field", color: COLORS.field },
  { q: -11,  r: 10,  name: "Поле", type: "field", color: COLORS.field },
  { q: -11,  r: 11,  name: "Поле", type: "field", color: COLORS.field },
  { q: -11,  r: 6,  name: "Поле", type: "field", color: COLORS.field },
  { q: -12,  r: 6,  name: "Поле", type: "field", color: COLORS.field },
  { q: -10,  r: 13,  name: "Поле", type: "field", color: COLORS.field },
  { q: -10,  r: 7,  name: "Поле", type: "field", color: COLORS.field },
  { q: -10,  r: 8,  name: "Поле", type: "field", color: COLORS.field },
  { q: -10,  r: 9,  name: "Поле", type: "field", color: COLORS.field },
  { q: -10,  r: 10,  name: "Поле", type: "field", color: COLORS.field },
  { q: -10,  r: 6,  name: "Поле", type: "field", color: COLORS.field },
  { q: -8,  r: 9,  name: "Поле", type: "field", color: COLORS.field },
  { q: -8,  r: 10,  name: "Поле", type: "field", color: COLORS.field },
  { q: -8,  r: 11,  name: "Поле", type: "field", color: COLORS.field },
  { q: -7,  r: 8,  name: "Поле", type: "field", color: COLORS.field },
  { q: -7,  r: 10,  name: "Поле", type: "field", color: COLORS.field },
  { q: -9,  r: 8,  name: "Поле", type: "field", color: COLORS.field },
  { q: -9,  r: 9,  name: "Поле", type: "field", color: COLORS.field },
  { q: -9,  r: 10,  name: "Поле", type: "field", color: COLORS.field },
  { q: -8,  r: 5,  name: "Поле", type: "field", color: COLORS.field },
  { q: -8,  r: 6,  name: "Поле", type: "field", color: COLORS.field },


  //
  // Леса
  //
  { q: -1,  r: 4,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -1,  r: 10,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -1,  r: 11,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 2,  r: 1,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 3,  r: 1,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 4,  r: 1,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 4,  r: 2,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 0,  r: 2,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 0,  r: 3,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 0,  r: 5,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 0,  r: 6,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 0,  r: 8,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 0,  r: 9,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 0,  r: 10,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 0,  r: 11,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 1,  r: 2,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 1,  r: 3,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 1,  r: 4,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 1,  r: 5,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 1,  r: 8,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 1,  r: 11,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 2,  r: 8,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 2,  r: 9,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 2,  r: 10,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 2,  r: 11,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 3,  r: 9,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 3,  r: 10,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 5,  r: 0,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 6,  r: 0,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 7,  r: 0,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 8,  r: 0,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 5,  r: 1,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 6,  r: 1,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 7,  r: 1,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 5,  r: 2,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 6,  r: 2,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 6,  r: -1,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 0,  r: -2,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 3,  r: -2,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 4,  r: -2,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 5,  r: -2,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -1,  r: -3,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 0,  r: -3,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 1,  r: -3,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 2,  r: -3,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 3,  r: -3,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 4,  r: -3,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 5,  r: -3,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 6,  r: -3,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -1,  r: -4,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 0,  r: -4,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 1,  r: -4,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 2,  r: -4,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 3,  r: -4,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 4,  r: -4,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 5,  r: -4,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 6,  r: -4,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 0,  r: -5,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 1,  r: -5,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 2,  r: -5,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 3,  r: -5,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 4,  r: -5,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 5,  r: -5,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 6,  r: -5,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 1,  r: -6,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 2,  r: -6,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 3,  r: -6,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 4,  r: -6,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 5,  r: -6,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 6,  r: -6,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 1,  r: -7,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 2,  r: -7,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 3,  r: -7,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 4,  r: -7,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 5,  r: -7,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 6,  r: -7,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 7,  r: -7,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 0,  r: 12,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 0,  r: 13,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: 1,  r: 12,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -1,  r: 12,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -2,  r: 12,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -2,  r: 13,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -2,  r: 15,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -1,  r: 14,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -3,  r: 14,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -3,  r: 15,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -7,  r: 11,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -7,  r: 12,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -8,  r: 12,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -5,  r: 11,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -5,  r: 12,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -5,  r: 13,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -6,  r: 11,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -6,  r: 13,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -6,  r: 6,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -6,  r: 7,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -6,  r: 8,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -6,  r: 9,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -6,  r: 10,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -7,  r: 5,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -7,  r: 6,  name: "Лес", type: "forest", color: COLORS.forest },
  { q: -7,  r: 7,  name: "Лес", type: "forest", color: COLORS.forest },

  //
  // Реки
  //
  { q: 0,  r: 7,  name: "Горловка", type: "river", color: COLORS.river },
  { q: 1,  r: 6,  name: "Горловка", type: "river", color: COLORS.river },
  { q: 1,  r: 7,  name: "Горловка", type: "river", color: COLORS.river },
  { q: 2,  r: 7,  name: "Горловка", type: "river", color: COLORS.river },
  { q: 3,  r: 7,  name: "Горловка", type: "river", color: COLORS.river },
  { q: 3,  r: 8,  name: "Горловка", type: "river", color: COLORS.river },
  { q: 4,  r: 6,  name: "Горловка", type: "river", color: COLORS.river },
  { q: 5,  r: 6,  name: "Горловка", type: "river", color: COLORS.river },
  { q: 6,  r: 5,  name: "Горловка", type: "river", color: COLORS.river },
  { q: 7,  r: 5,  name: "Горловка", type: "river", color: COLORS.river },
  { q: 8,  r: 3,  name: "Горловка", type: "river", color: COLORS.river },
  { q: 8,  r: 4,  name: "Горловка", type: "river", color: COLORS.river },
  { q: -6,  r: 14,  name: "Рось", type: "river", color: COLORS.river },
  { q: -7,  r: 14,  name: "Рось", type: "river", color: COLORS.river },
  { q: -7,  r: 13,  name: "Рось", type: "river", color: COLORS.river },
  { q: -8,  r: 13,  name: "Рось", type: "river", color: COLORS.river },
  { q: -9,  r: 13,  name: "Рось", type: "river", color: COLORS.river },
  { q: -6,  r: 12,  name: "Рось", type: "river", color: COLORS.river },
  { q: -10,  r: 14,  name: "Рось", type: "river", color: COLORS.river },
  { q: -9,  r: 12,  name: "Рось", type: "river", color: COLORS.river },
  { q: -9,  r: 11,  name: "Рось", type: "river", color: COLORS.river },
  { q: -10,  r: 11,  name: "Рось", type: "river", color: COLORS.river },
  { q: -11,  r: 12,  name: "Рось", type: "river", color: COLORS.river },
  { q: -12,  r: 12,  name: "Рось", type: "river", color: COLORS.river },
  { q: -13,  r: 12,  name: "Рось", type: "river", color: COLORS.river },
  { q: -13,  r: 11,  name: "Рось", type: "river", color: COLORS.river },

  //
  // Днепр
  //
  { q: -2,  r: 4,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -3,  r: 4,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -4,  r: 4,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -4,  r: 4,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -5,  r: 4,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -6,  r: 4,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -7,  r: 4,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -2,  r: 5,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -5,  r: 5,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -6,  r: 5,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -3,  r: 6,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -4,  r: 6,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -5,  r: 6,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -1,  r: 5,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -1,  r: 6,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -1,  r: 7,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -1,  r: 8,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -5,  r: 7,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -5,  r: 8,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -5,  r: 9,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -5,  r: 10,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -4,  r: 10,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -4,  r: 11,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -3,  r: 11,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -2,  r: 11,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -2,  r: 10,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -1,  r: 9,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -6,  r: -2,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -2,  r: -5,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -6,  r: -1,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -6,  r: 0,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -6,  r: 1,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -6,  r: 2,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -6,  r: 3,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -7,  r: -1,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -7,  r: 0,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -7,  r: 1,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -7,  r: 2,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -7,  r: 3,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -2,  r: 1,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -2,  r: 2,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -2,  r: 3,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -3,  r: -4,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -3,  r: -5,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -2,  r: -4,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -2,  r: -3,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -2,  r: -2,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -2,  r: -1,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -2,  r: 0,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -4,  r: 13,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -4,  r: 12,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -3,  r: 13,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -5,  r: 14,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -3,  r: 12,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -4,  r: 14,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -5,  r: 15,  name: "Днепр", type: "great_river", color: COLORS.great_river },
  { q: -4,  r: 15,  name: "Днепр", type: "great_river", color: COLORS.great_river },

  //
  // Острова и Заводи Днепра
  //
  { q: -3,  r: 0,  name: "Заводи Днепра", type: "lough_river", color: COLORS.lough_river },
  { q: -3,  r: 1,  name: "Заводи Днепра", type: "lough_river", color: COLORS.lough_river },
  { q: -4,  r: 2,  name: "Заводи Днепра", type: "lough_river", color: COLORS.lough_river },
  { q: -4,  r: 3,  name: "Заводи Днепра", type: "lough_river", color: COLORS.lough_river },
  { q: -2,  r: 8,  name: "Заводи Днепра", type: "lough_river", color: COLORS.lough_river },
  { q: -2,  r: 9,  name: "Заводи Днепра", type: "lough_river", color: COLORS.lough_river },
  { q: -3,  r: 7,  name: "Заводи Днепра", type: "lough_river", color: COLORS.lough_river },
  { q: -3,  r: 8,  name: "Заводи Днепра", type: "lough_river", color: COLORS.lough_river },
  { q: -3,  r: 9,  name: "Заводи Днепра", type: "lough_river", color: COLORS.lough_river },
  { q: -3,  r: 10,  name: "Заводи Днепра", type: "lough_river", color: COLORS.lough_river },
  { q: -4,  r: -4,  name: "Заводи Днепра", type: "lough_river", color: COLORS.lough_river },
  { q: -5,  r: -3,  name: "Заводи Днепра", type: "lough_river", color: COLORS.lough_river },

  { q: -3,  r: -3,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -4,  r: -3,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -3,  r: -2,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -4,  r: -2,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -5,  r: -2,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -3,  r: -1,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -5,  r: -1,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -4,  r: 0,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -5,  r: 0,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -4,  r: 1,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -5,  r: 1,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -3,  r: 2,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -5,  r: 2,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -3,  r: 3,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -5,  r: 3,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -3,  r: 5,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -4,  r: 5,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -2,  r: 6,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -2,  r: 7,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -4,  r: 7,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -4,  r: 8,  name: "Острова Днепра", type: "island", color: COLORS.island },
  { q: -4,  r: 9,  name: "Острова Днепра", type: "island", color: COLORS.island },


];

export default mapData;
